
/*
# This file is included as a preface to every transpiled code.
*/

CREATE FUNCTION GRASP_VARIANT_ARRAY_DROP_SIDES(array VARIANT ARRAY, drop_on_left INTEGER UNSIGNED, drop_on_right INTEGER UNSIGNED) RETURNS VARIANT ARRAY;
CREATE FUNCTION GRASP_TEXT_ARRAY_DROP_SIDES(array TEXT ARRAY, drop_on_left INTEGER UNSIGNED, drop_on_right INTEGER UNSIGNED) RETURNS TEXT ARRAY;
