

CREATE FUNCTION GRASP_TEXT_ARRAY_DROP_LEFT(array TEXT ARRAY, num INTEGER UNSIGNED) RETURNS TEXT ARRAY;

CREATE FUNCTION GRASP_TEXT_ARRAY_DROP_RIGHT(array TEXT ARRAY, num INTEGER UNSIGNED) RETURNS TEXT ARRAY;